version: "3"
services:
  calibre-web:
    image: linuxserver/calibre-web:0.6.4-ls40
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${timezone}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /home/ubuntu/config:/config
      - /home/ubuntu/books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
